### ISSUE TITLE
"changeme" in ApiThumbnailsBundle/DependencyInjection/Configuration.php

### ISSUE THREAD

**Issue by TimPietrusky** [synoa/cerebro.pimcore.thumbnail#2]
I updated https://github.com/synoa/cerebro.pimcore.thumbnail/commit/d86afc64a9d6930970bbc551d298bc8791f1bf69 so that instead of `changeme` we are using the word `api_thumbnails`.

Is that ok?

**Comment by dpfaffenbauer** [comment]
that is not used anyway, since symfony controls that here, but it is fine anway

**Comment by TimPietrusky** [comment]
@dpfaffenbauer I received an error during installation of Pimcore that the variable with the name `changeme` doesn't exist. That's why I updated this. Do you have an idea why this is happening?

**Comment by dpfaffenbauer** [comment]
not really...

**Comment by dpfaffenbauer** [comment]
But it works now, doesn't it? so we can consider this fixed anyway, right

**Comment by TimPietrusky** [comment]
@dpfaffenbauer yes!
